# -*- coding: utf-8 -*-
"""Lab1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TwtoF0emCz3JlwKeH7HI0U5GaKJY1e21
"""

from google.colab import drive

drive.mount('/content/gdrive')

!ls '/content/gdrive/My Drive/CMPUT 206 Wi19/Lab1_Files/'
filename_Test = '/content/gdrive/My Drive/CMPUT 206 Wi19/Lab1_Files/test.jpg'
filename_Day = '/content/gdrive/My Drive/CMPUT 206 Wi19/Lab1_Files/day.jpg'
filename_Night = '/content/gdrive/My Drive/CMPUT 206 Wi19/Lab1_Files/night.jpg'

#Your Code 
import numpy as np 
from scipy import ndimage, misc
from skimage import io, exposure, img_as_ubyte
import matplotlib.pyplot as plt
import matplotlib.image as mpimg



def main():
    imgIn = img_as_ubyte(io.imread(filename_Test, True))
    print("HERE IS PART 1")
    part1(imgIn)
    

    
    
    
def part1(imgIn):

    #using my own histogram fxn
    myHist(imgIn)
    
    #using the built in histogram fxn
    builtInHist(imgIn)
    
def myHist(FILE):
    imgArray = np.zeros(256, dtype=int)

    for i in FILE:
        for j in i:
            imgArray[j]+=1

    plt.xlim(0,256)
    plt.plot(imgArray)
    
    plt.show()
    N = len(FILE)
    M = len(FILE[0])

            
def builtInHist(FILE):
    A = exposure.histogram(FILE, nbins=256)
    plt.xlim(0,256)
    plt.plot(A[1], A[0])
    plt.show()
  
  
main()

def main2():
    FILE = img_as_ubyte(io.imread(filename_Test, True))
    myHist(FILE)
    part2(FILE)
    
    
    
def myHist(FILE):
    imgArray = np.zeros(256, dtype=int)

    for i in FILE:
        for j in i:
            imgArray[j]+=1
    plt.imshow(FILE)
    plt.show()
    plt.xlim(0,256)
    plt.plot(imgArray)
    
    plt.show()
    
    
def part2(FILE):
    imgArray = np.zeros(256, dtype=int)

    for i in FILE:
        for j in i:
            imgArray[j]+=1
    
    M = len(FILE)
    N = len(FILE[0])
    
    #compute the cumulative histogram
    #a'=floor[(k-1)/MN * H(a) + 0.5]
    
    newFILE = FILE
    sumCum = np.cumsum(imgArray)
    
    MN = M*N
   
    for i in range(M):
        for j in range(N):
            newFILE[i][j] = np.floor( ((255/MN)* sumCum[FILE[i][j]]) + 0.5)
        
    plt.imshow(newFILE)
    plt.show()
    
    newArray = np.zeros(256, dtype=int)
    for i in newFILE:
        for j in i:
            newArray[j]+=1
    plt.xlim(0,256)
    plt.plot(newArray)
    plt.show()
    

   
    
main2()